# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import client
import server
from PyQt5 import QtCore, QtGui, QtWidgets





class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 698)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.s_ip_lbl = QtWidgets.QLabel(self.centralwidget)
        self.s_ip_lbl.setGeometry(QtCore.QRect(100, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s_ip_lbl.setFont(font)
        self.s_ip_lbl.setObjectName("s_ip_lbl")
        self.sip_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.sip_txt.setGeometry(QtCore.QRect(320, 70, 113, 22))
        self.sip_txt.setObjectName("sip_txt")
        self.s_pn_lbl = QtWidgets.QLabel(self.centralwidget)
        self.s_pn_lbl.setGeometry(QtCore.QRect(100, 110, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.s_pn_lbl.setFont(font)
        self.s_pn_lbl.setObjectName("s_pn_lbl")
        self.spn_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.spn_txt.setGeometry(QtCore.QRect(320, 110, 113, 22))
        self.spn_txt.setObjectName("spn_txt")
        self.c_ip_lbl = QtWidgets.QLabel(self.centralwidget)
        self.c_ip_lbl.setGeometry(QtCore.QRect(100, 150, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c_ip_lbl.setFont(font)
        self.c_ip_lbl.setObjectName("c_ip_lbl")
        self.cip_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.cip_txt.setGeometry(QtCore.QRect(320, 150, 113, 22))
        self.cip_txt.setObjectName("cip_txt")
        self.c_pn_lbl = QtWidgets.QLabel(self.centralwidget)
        self.c_pn_lbl.setGeometry(QtCore.QRect(100, 190, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.c_pn_lbl.setFont(font)
        self.c_pn_lbl.setObjectName("c_pn_lbl")
        self.cpn_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.cpn_txt.setGeometry(QtCore.QRect(320, 190, 113, 22))
        self.cpn_txt.setObjectName("cpn_txt")
        self.rtc_lbl = QtWidgets.QLabel(self.centralwidget)
        self.rtc_lbl.setGeometry(QtCore.QRect(100, 230, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rtc_lbl.setFont(font)
        self.rtc_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.rtc_lbl.setObjectName("rtc_lbl")
        self.gt_lbl = QtWidgets.QLabel(self.centralwidget)
        self.gt_lbl.setGeometry(QtCore.QRect(100, 270, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gt_lbl.setFont(font)
        self.gt_lbl.setObjectName("gt_lbl")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 430, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pktsize_lbl = QtWidgets.QLabel(self.centralwidget)
        self.pktsize_lbl.setGeometry(QtCore.QRect(100, 350, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pktsize_lbl.setFont(font)
        self.pktsize_lbl.setObjectName("pktsize_lbl")
        self.reqfile_lbl = QtWidgets.QLabel(self.centralwidget)
        self.reqfile_lbl.setGeometry(QtCore.QRect(100, 390, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reqfile_lbl.setFont(font)
        self.reqfile_lbl.setObjectName("reqfile_lbl")
        self.rtt_lbl = QtWidgets.QLabel(self.centralwidget)
        self.rtt_lbl.setGeometry(QtCore.QRect(100, 310, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rtt_lbl.setFont(font)
        self.rtt_lbl.setObjectName("rtt_lbl")
        self.rtc_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.rtc_txt.setGeometry(QtCore.QRect(320, 230, 113, 22))
        self.rtc_txt.setObjectName("rtc_txt")
        self.gt_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.gt_txt.setGeometry(QtCore.QRect(320, 270, 113, 22))
        self.gt_txt.setObjectName("gt_txt")
        self.rtt_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.rtt_txt.setGeometry(QtCore.QRect(320, 310, 113, 22))
        self.rtt_txt.setObjectName("rtt_txt")
        self.pktsize_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.pktsize_txt.setGeometry(QtCore.QRect(320, 350, 113, 22))
        self.pktsize_txt.setObjectName("pktsize_txt")
        self.reqfile_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.reqfile_txt.setGeometry(QtCore.QRect(320, 390, 113, 22))
        self.reqfile_txt.setObjectName("reqfile_txt")
        self.winsize_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.winsize_txt.setGeometry(QtCore.QRect(320, 430, 113, 22))
        self.winsize_txt.setObjectName("winsize_txt")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(110, 540, 321, 71))
        self.textBrowser.setObjectName("textBrowser")

        self.cbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cbtn.setGeometry(QtCore.QRect(180, 480, 171, 28))
        self.cbtn.setObjectName("cbtn")
        self.cbtn.clicked.connect(self.button_clicked)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.s_ip_lbl.setText(_translate("MainWindow", "Server IP Address"))
        self.s_pn_lbl.setText(_translate("MainWindow", "Server Port Number"))
        self.c_ip_lbl.setText(_translate("MainWindow", "Client IP Address"))
        self.c_pn_lbl.setText(_translate("MainWindow", "Client Port Number"))
        self.rtc_lbl.setText(_translate("MainWindow", "Re-Transmission Count"))
        self.gt_lbl.setText(_translate("MainWindow", "Glabal Timer"))
        self.label.setText(_translate("MainWindow", "Window Size"))
        self.pktsize_lbl.setText(_translate("MainWindow", "Packet Size"))
        self.reqfile_lbl.setText(_translate("MainWindow", "Requested File"))
        self.rtt_lbl.setText(_translate("MainWindow", "Re-Transmission Timer"))
        self.cbtn.setText(_translate("MainWindow", "Start Client"))


    def button_clicked(self):
        server_ip = self.sip_txt.text()
        client_ip = self.cip_txt.text()
        server_port = self.spn_txt.text()
        client_port = self.spn_txt.text()
        transfer_file = self.reqfile_txt.text()
        s1 = server.Server(server_ip,server_port,client_ip,client_port)
        c1 = client.Client(client_ip,client_port,server_ip,server_port,transfer_file)


   




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
